# Generated by Django 2.2.4 on 2019-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelethonEntity',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelethonSession',
            fields=[
                ('dc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('auth_key', models.BinaryField()),
                ('takeout_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelethonUpdateState',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('qts', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelethonSentFile',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('md5_digest', models.BinaryField()),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_type', models.IntegerField(blank=True, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('hash', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('md5_digest', 'file_size', 'file_type')},
            },
        ),
    ]
