# Generated by Django 2.2.4 on 2019-12-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telethon_session', '0001_initial')
    ]

    operations = [
        migrations.AddField(
            model_name='TelethonSession',
            name='client_session_name',
            field=models.CharField(blank=False, default='default_client', max_length=1000, null=False),
        ),
        migrations.AddField(
            model_name='TelethonEntity',
            name='client_session_name',
            field=models.CharField(blank=False, default='default_client', max_length=1000, null=False),
        ),
        migrations.AddField(
            model_name='TelethonUpdateState',
            name='client_session_name',
            field=models.CharField(blank=False, default='default_client', max_length=1000, null=False),
        ),
        migrations.AddField(
            model_name='TelethonSentFile',
            name='client_session_name',
            field=models.CharField(blank=False, default='default_client', max_length=1000, null=False),
        ),
        migrations.AlterUniqueTogether(
            name='TelethonSentFile',
            unique_together={('client_session_name', 'md5_digest', 'file_size', 'file_type')},
        ),
    ]
